project:
  type: website
  output-dir: docs

website:
  title: "Informática Estadística 2"
  page-navigation: true
  back-to-top-navigation: true
  sidebar:
    background: "#24639A"
    logo: img/untref_logo.jpg
    search: true
    left:
      - text: "Inicio"
        file: index.qmd
      - text: "Intro"
        file: intro.qmd
      - text: "Resumen"
        file: summary.qmd
      - text: "Referencias"
        file: references.qmd
  page-footer: 
    left: "Copyright 2024, UNTREF" 
    right: 
      - icon: github
        href: https://github.com/LeanColisko/InformaticaEstadisticaUntref
    background: "#24639A"

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

