project:
  type: website
  output-dir: docs

website:
  title: "Informática Estadística 2"
  page-navigation: true
  back-to-top-navigation: false
  sidebar:
    background: "#24639A"
    logo: "img/untref_logo.jpg"
    pinned: false
    align: center
    search: true
    style: "docked"
    contents:
      - text: "Inicio"
        href: pages/index.qmd
      - text: "Intro"
        href: pages/intro.qmd
      - text: "Resumen"
        href: pages/summary.qmd
        
  page-footer: 
    left: "Copyright 2024, UNTREF" 
    right: 
      - icon: github
        href: https://github.com/LeanColisko/InformaticaEstadisticaUntref
    background: "#24639A"

format:
  html:
    theme: cosmo

editor: visual

