project:
  type: website
  output-dir: docs

website:
  title: "Informática Estadística 2"
  page-navigation: true
  back-to-top-navigation: true
  sidebar:
    background: "#24639A"
    logo: "img/untref_logo.jpg"
    pinned: false
    align: center
    search: true
    style: "docked"
    collapse-level: 1
    contents:
      - text: "Inicio"
        href: pages/index.qmd
      - text: "Regresión Logísitca"
        href: pages/regresion_logistica.qmd
      - text: "Cluster Jerarquico"
        href: pages/Clusters.qmd
        
  page-footer: 
    left: "2024 - UNTREF" 
    right: 
      - icon: github
        href: https://github.com/LeanColisko/InformaticaEstadisticaUntref
    background: "#24639A"

format:
  html:
    theme: cosmo

editor: visual

